### ISSUE TITLE
UPDATE: I didn't know that sqlscripts under src\SQL\ folder were obsolete, please delete that folder

### ISSUE THREAD

**Issue by vegax87** [Elfocrash/L2dotNET#35]
I found it rather confusing because our accounts table is structured with `account` and `password` while in AccountRepository.cs there are a few references about this "login" column which is not present in src\SQL\LoginServer\accounts.sql

return Db.Query<AccountModel>("select **Login**,Password,LastActive,access_level as AccessLevel,LastServer from accounts where login=@login"

return Db.Query("select distinct 1 from accounts where **login**=@login AND password=@pass")
#

**Comment by MartLegion** [comment]
We use this .sql

**Comment by vegax87** [comment]
Got it, that \src\SQL folder is misleading
