### ISSUE TITLE
The log - Issue?

### ISSUE THREAD

**Issue by machado-rev** [Elfocrash/L2dotNET#37]
Hi, how are you guys?

I put a server online for test purpose and look what I find into the log:

INFO  2017-06-22 17:37:18,496 633906ms GameServer             OnClientConnected  Received connection request from: 198.199.98.246:55213
INFO  2017-06-22 17:37:18,502 633912ms GameClient             .ctor              connection from 198.199.98.246:55213
INFO  2017-06-22 17:37:18,503 633913ms ClientManager          AddClient          NetController: 1 active connections

What is this? Why a IP from California tried to connect?

**Comment by machado-rev** [comment]
I just set to accept ips not ALL with *!

Now I have an issue with external login.

look:

![image](https://user-images.githubusercontent.com/3827247/27458836-60babbda-5781-11e7-9e04-6c0482b13f0c.png)

**Comment by machado-rev** [comment]
Sorry for the "Flood" but I am testing and I will TEST ALOT this system and contribute.

I solved the ping problem, now I have another issue. 

The log show this message:
`ServerRepository       GetPlayerSkills    Method: GetPlayerSkills. Message: 'Table 'guarani.user_skills' doesn't exist' (Error Number: '1146')`


I will try figure what is this, but if I don't find I will try to create an SQL file.

Thank you

**Comment by machado-rev** [comment]
Solved, I adapted an L2jAcis database character_skills.sql to user_skills.sql and the result was:

```
CREATE TABLE IF NOT EXISTS `user_skills` (
  `char_obj_id` INT UNSIGNED NOT NULL default 0,
  `skill_id` INT NOT NULL default 0,
  `skill_level` INT(3) NOT NULL default 1,
  `class_index` INT(1) NOT NULL DEFAULT 0,
  `ownerId` INT(3) NOT NULL DEFAULT 0,
  `id` INT(1) NOT NULL DEFAULT 0,
  `lvl` INT(3) NOT NULL default 1,
  `iclass` INT UNSIGNED NOT NULL default 0,
  PRIMARY KEY (`char_obj_id`,`skill_id`,`class_index`)
);

```

Need a clean but works

Now I need see into the cs codes to start adding a class.

I'll try to add manually to test

**Comment by Elfocrash** [comment]
Skills are not ready and i would recommend not to mess with it too much until i have a look at it.

First i have to do normal auto attack and then skills and skill trees.

**Comment by machado-rev** [comment]
Elfo, hello!

What can I do to help?

I will enter again into github chat.
