### ISSUE TITLE
Access failed, please try again later...

### ISSUE THREAD

**Issue by gio-abashidze** [Elfocrash/L2dotNET#45]
when i try to login, i'm getting this error: Acces failed, please try again later...

i tried to change server port in server.json file but after start the server it's changin back to 2106

any ideas?

**Comment by Elfocrash** [comment]
Any console logs?

**Comment by gio-abashidze** [comment]
no logs

**Comment by Elfocrash** [comment]
There is no way you are getting an access failed without something printed in the console.

**Comment by gio-abashidze** [comment]
The thread 0x2b80 has exited with code 0 (0x0). this is the output in visual studio, this message prints out in every 20 second, with different addresses

**Comment by gio-abashidze** [comment]
and nothing more

**Comment by gio-abashidze** [comment]
there is only loginserver.exe and no gameserver.exe in project, i don't need to run gameserver?

**Comment by gio-abashidze** [comment]
sorry i found gameserver and there was error:
Unhandled Exception: System.TypeInitializationException: The type initializer for 'L2dotNET.GameService.Program' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies. The system cannot find the file specified.
   at L2dotNET.GameService.Program..cctor()
   --- End of inner exception stack trace ---
   at L2dotNET.GameService.Program.Main()

**Comment by gio-abashidze** [comment]
but i have installed nugged package log4net 2.8

**Comment by Elfocrash** [comment]
can you please run both gameserver and loginserver? They are different projects

**Comment by gio-abashidze** [comment]
if i run loginserver from visual studio there is no problem but when i run it from exe there is also log4net error

**Comment by gio-abashidze** [comment]
now  i got both running there is 2 error in gameserver:
ERROR - ScriptCompiler: Failed to compile cmpl\quests\_0001_letters_of_love.cs.
ERROR - ScriptCompiler: Failed to compile cmpl\quests\_0002_what_women_want.cs.
but server is u pand running i think

**Comment by Elfocrash** [comment]
Those are workings. Server should be running

**Comment by gio-abashidze** [comment]
i don't know what is the problwm, this is ip and port that loginserver listens from clients 127.0.0.1:2106 and i changed it in l2.ini and i got gameserver and loginserver running.. but can't login

**Comment by Elfocrash** [comment]
you are using interlude client right?

**Comment by gio-abashidze** [comment]
yes

**Comment by gio-abashidze** [comment]
now i changed the system folder and got different problem :d I changed ip and port in l2.ini but it still connects server that i downloaded the system from.

**Comment by Elfocrash** [comment]
Because it uses a different way to point the IP through it's client protection. Download a clean system

**Comment by gio-abashidze** [comment]
i did. thanks. https://www.4shared.com/rar/wT95ZOhWce/clean_system.html here is a clean system.

**Comment by gio-abashidze** [comment]
can you send me a tree of classes?
