### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by infereno** [Elfocrash/L2dotNET#50]
it looks like something is very wrong in l2Character

if (this is L2Player player)
            {
                if (broadcastFull)
                {
                    player.UpdateAndBroadcastStatus(2);
                }
                else
                {
                    player.UpdateAndBroadcastStatus(1);
                    if (statusUpdate != null)
                        BroadcastPacket(statusUpdate);
                }
            }

there is no variable named player and the syntax doesnt seem right
can you point me inte the right direction?

**Comment by Elfocrash** [comment]
The player variable is created at this line `if (this is L2Player player)`
