### ISSUE TITLE
There is no "wait" keyword in asynchronous calls

### ISSUE THREAD

**Issue by iamkisly** [Elfocrash/L2dotNET#73]
https://github.com/Elfocrash/L2dotNET/blob/7a98b20095d5cc5dc53c1617b760fd8574c12039/src/L2dotNET.LoginService/Network/OuterNetwork/RequestPackets/AuthGameGuard.cs#L33

Add the keyword "await" or replace the send with synchronous. The same problem in the rest of the files in this folder.

**Comment by Elfocrash** [comment]
This is known. I was in the process of changing the sync networking pipeline to an async one but never got around to finish it, that's why there are thousands of calls like this that are not awaited.
